# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.cache/wt [current_project]
set_property parent.project_path D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/ip_repo/myip_3.0
  d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/ip_repo/myip_2.0
  d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/ip_repo/myip_1.0
  d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/ip_repo/myip_1.0
} [current_project]
set_property ip_output_repo d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/sources_1/bd/system/system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/constrs_1/imports/rtl/ps_pl.xdc
set_property used_in_implementation false [get_files D:/Users/jmcui/workspace/ps_pl6/ps_pl6/ps_pl/hw_proj/project/project.srcs/constrs_1/imports/rtl/ps_pl.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
